services:
  db:
    image: postgres:17
    container_name: bookstore-db
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bookstore"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bookstore-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  postgres_data:
